#pragma once

#include "Types.h"

#include <array>
#include <string>

namespace gm
{
	enum class QamilAnimationId : uint32
	{
		Phase2Start,
		MissileReady,
		Missile1,
		Missile2,
		Missile3,
		Missile4,
		MissileGo,
		Laser,
		LaserRebound,
		LaserRestore,
		Ddakqong,
		Stump,
		Wooth,
		MooyahoToWoong,

		ChainWoothToLeftReady,
		ChainLeftReadyToLeftFar,
		ChainLeftFarToLeftReady,
		ChainLeftFarToRightReady,
		ChainLeftReadyToLeftFarFinisher,
		ChainLeftFarFinisherToWait,
		ChainLeftFarFinisherToMooyaho,
		ChainLeftReadyToLeftNear,
		ChainLeftNearToLeftReady,
		ChainLeftNearToRightReady,
		ChainLeftReadyToLeftNearFinisher,
		ChainLeftNearFinisherToWait,
		ChainLeftNearFinisherToMooyaho,
		ChainLeftReadyToLeftOuterFar,
		ChainLeftOuterFarToLeftReady,
		ChainLeftOuterFarToRightReady,
		ChainLeftReadyToLeftOuterFarFinisher,
		ChainLeftOuterFarFinisherToWait,
		ChainLeftOuterFarFinisherToMooyaho,
		ChainLeftReadyToLeftOuterNear,
		ChainLeftOuterNearToLeftReady,
		ChainLeftOuterNearToRightReady,
		ChainLeftReadyToLeftOuterNearFinisher,
		ChainLeftOuterNearFinisherToWait,
		ChainLeftOuterNearFinisherToMooyaho,

		ChainWoothToRightReady,
		ChainRightReadyToRightFar,
		ChainRightFarToLeftReady,
		ChainRightFarToRightReady,
		ChainRightReadyToRightFarFinisher,
		ChainRightFarFinisherToWait,
		ChainRightFarFinisherToMooyaho,
		ChainRightReadyToRightNear,
		ChainRightNearToLeftReady,
		ChainRightNearToRightReady,
		ChainRightReadyToRightNearFinisher,
		ChainRightNearFinisherToWait,
		ChainRightNearFinisherToMooyaho,
		ChainRightReadyToRightOuterFar,
		ChainRightOuterFarToLeftReady,
		ChainRightOuterFarToRightReady,
		ChainRightReadyToRightOuterFarFinisher,
		ChainRightOuterFarFinisherToWait,
		ChainRightOuterFarFinisherToMooyaho,
		ChainRightReadyToRightOuterNear,
		ChainRightOuterNearToLeftReady,
		ChainRightOuterNearToRightReady,
		ChainRightReadyToRightOuterNearFinisher,
		ChainRightOuterNearFinisherToWait,
		ChainRightOuterNearFinisherToMooyaho,

		SweepLeft,
		NormalLeftFar,
		NormalLeftFarWait,
		NormalLeftFarRestore,
		NormalLeftNear,
		NormalLeftNearWait,
		NormalLeftNearRestore,
		NormalLeftOuterFar,
		NormalLeftOuterFarWait,
		NormalLeftOuterFarRestore,
		NormalLeftOuterNear,
		NormalLeftOuterNearWait,
		NormalLeftOuterNearRestore,
		NormalRightFar,
		NormalRightFarWait,
		NormalRightFarRestore,
		NormalRightNear,
		NormalRightNearWait,
		NormalRightNearRestore,
		NormalRightOuterFar,
		NormalRightOuterFarWait,
		NormalRightOuterFarRestore,
		NormalRightOuterNear,
		NormalRightOuterNearWait,
		NormalRightOuterNearRestore,
		SweepRight,
		Idle,
		MoveLeftStart,
		MoveLeft,
		MoveLeftEnd,
		MoveRightStart,
		MoveRight,
		MoveRightEnd,

		Count,
	};

	inline constexpr uint32 ToIndex(QamilAnimationId animationId)
	{
		return static_cast<uint32>(animationId);
	}

	inline constexpr uint32 QamilAnimationIdCount = ToIndex(QamilAnimationId::Count);

	inline constexpr std::array<const wchar_t*, QamilAnimationIdCount> QamilAnimationClipNames =
	{
		L"ANIM_PHASE2_START",
		L"ANIM_MISSILE_READY",
		L"ANIM_MISSILE_1",
		L"ANIM_MISSILE_2",
		L"ANIM_MISSILE_3",
		L"ANIM_MISSILE_4",
		L"ANIM_MISSILE_GO",
		L"ANIM_LASER",
		L"ANIM_LASER_REBOUND",
		L"ANIM_LASER_RESTORE",
		L"ANIM_DDAKQONG",
		L"ANIM_STUMP",
		L"ANIM_WOOTH",
		L"ANIM_MOOYAHO_TO_WOONG",

		L"ANIM_CHAIN_WOOTH_TO_LEFT_READY",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_FAR",
		L"ANIM_CHAIN_LEFT_FAR_TO_LEFT_READY",
		L"ANIM_CHAIN_LEFT_FAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_FAR_FINISHER",
		L"ANIM_CHAIN_LEFT_FAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_LEFT_FAR_FINISHER_TO_MOOYAHO",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_NEAR",
		L"ANIM_CHAIN_LEFT_NEAR_TO_LEFT_READY",
		L"ANIM_CHAIN_LEFT_NEAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_NEAR_FINISHER",
		L"ANIM_CHAIN_LEFT_NEAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_LEFT_NEAR_FINISHER_TO_MOOYAHO",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_OUTER_FAR",
		L"ANIM_CHAIN_LEFT_OUTER_FAR_TO_LEFT_READY",
		L"ANIM_CHAIN_LEFT_OUTER_FAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_OUTER_FAR_FINISHER",
		L"ANIM_CHAIN_LEFT_OUTER_FAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_LEFT_OUTER_FAR_FINISHER_TO_MOOYAHO",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_OUTER_NEAR",
		L"ANIM_CHAIN_LEFT_OUTER_NEAR_TO_LEFT_READY",
		L"ANIM_CHAIN_LEFT_OUTER_NEAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_LEFT_READY_TO_LEFT_OUTER_NEAR_FINISHER",
		L"ANIM_CHAIN_LEFT_OUTER_NEAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_LEFT_OUTER_NEAR_FINISHER_TO_MOOYAHO",

		L"ANIM_CHAIN_WOOTH_TO_RIGHT_READY",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_FAR",
		L"ANIM_CHAIN_RIGHT_FAR_TO_LEFT_READY",
		L"ANIM_CHAIN_RIGHT_FAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_FAR_FINISHER",
		L"ANIM_CHAIN_RIGHT_FAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_RIGHT_FAR_FINISHER_TO_MOOYAHO",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_NEAR",
		L"ANIM_CHAIN_RIGHT_NEAR_TO_LEFT_READY",
		L"ANIM_CHAIN_RIGHT_NEAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_NEAR_FINISHER",
		L"ANIM_CHAIN_RIGHT_NEAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_RIGHT_NEAR_FINISHER_TO_MOOYAHO",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_OUTER_FAR",
		L"ANIM_CHAIN_RIGHT_OUTER_FAR_TO_LEFT_READY",
		L"ANIM_CHAIN_RIGHT_OUTER_FAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_OUTER_FAR_FINISHER",
		L"ANIM_CHAIN_RIGHT_OUTER_FAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_RIGHT_OUTER_FAR_FINISHER_TO_MOOYAHO",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_OUTER_NEAR",
		L"ANIM_CHAIN_RIGHT_OUTER_NEAR_TO_LEFT_READY",
		L"ANIM_CHAIN_RIGHT_OUTER_NEAR_TO_RIGHT_READY",
		L"ANIM_CHAIN_RIGHT_READY_TO_RIGHT_OUTER_NEAR_FINISHER",
		L"ANIM_CHAIN_RIGHT_OUTER_NEAR_FINISHER_TO_WAIT",
		L"ANIM_CHAIN_RIGHT_OUTER_NEAR_FINISHER_TO_MOOYAHO",

		L"ANIM_SWEEP_LEFT",
		L"ANIM_NORMAL_LEFT_FAR",
		L"ANIM_NORMAL_LEFT_FAR_WAIT",
		L"ANIM_NORMAL_LEFT_FAR_RESTORE",
		L"ANIM_NORMAL_LEFT_NEAR",
		L"ANIM_NORMAL_LEFT_NEAR_WAIT",
		L"ANIM_NORMAL_LEFT_NEAR_RESTORE",
		L"ANIM_NORMAL_LEFT_OUTER_FAR",
		L"ANIM_NORMAL_LEFT_OUTER_FAR_WAIT",
		L"ANIM_NORMAL_LEFT_OUTER_FAR_RESTORE",
		L"ANIM_NORMAL_LEFT_OUTER_NEAR",
		L"ANIM_NORMAL_LEFT_OUTER_NEAR_WAIT",
		L"ANIM_NORMAL_LEFT_OUTER_NEAR_RESTORE",
		L"ANIM_NORMAL_RIGHT_FAR",
		L"ANIM_NORMAL_RIGHT_FAR_WAIT",
		L"ANIM_NORMAL_RIGHT_FAR_RESTORE",
		L"ANIM_NORMAL_RIGHT_NEAR",
		L"ANIM_NORMAL_RIGHT_NEAR_WAIT",
		L"ANIM_NORMAL_RIGHT_NEAR_RESTORE",
		L"ANIM_NORMAL_RIGHT_OUTER_FAR",
		L"ANIM_NORMAL_RIGHT_OUTER_FAR_WAIT",
		L"ANIM_NORMAL_RIGHT_OUTER_FAR_RESTORE",
		L"ANIM_NORMAL_RIGHT_OUTER_NEAR",
		L"ANIM_NORMAL_RIGHT_OUTER_NEAR_WAIT",
		L"ANIM_NORMAL_RIGHT_OUTER_NEAR_RESTORE",
		L"ANIM_SWEEP_RIGHT",
		L"ANIM_IDLE",
		L"ANIM_MOVE_LEFT_START",
		L"ANIM_MOVE_LEFT",
		L"ANIM_MOVE_LEFT_END",
		L"ANIM_MOVE_RIGHT_START",
		L"ANIM_MOVE_RIGHT",
		L"ANIM_MOVE_RIGHT_END",
	};

	inline const wchar_t* GetQamilAnimationClipName(QamilAnimationId animationId)
	{
		return QamilAnimationClipNames[ToIndex(animationId)];
	}
}
